apps/accounts/urls.py
from django.urls import path
from .views import SetSpecial

app_name = "account"

urlpatterns = [
    path("set-special/",SetSpecial.as_view(),name="set-special")
]

apps/file/urls.py
from django.urls import path
from .views import FileList, AddFile, DetailFile, FileDownload, DeleteFile

app_name = "file"

urlpatterns = [
    path("", FileList.as_view(), name= "file-list"),
    path('add/',AddFile.as_view(),name="add-file"),
    path("detail/<int:id>/<str:slug>/", DetailFile.as_view(), name="file-detail"),
    path("download/<int:id>/<str:slug>/",FileDownload.as_view(),name="download-file"),
    path("delete/<int:id>/<str:slug>/", DeleteFile, name="delete-file")
]

uploader/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path("",include("apps.file.urls")),
    path("user/",include("apps.accounts.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'accounts.views.handler404'

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import UserManager


class User(AbstractUser):
    email = models.EmailField(unique=True, max_length=150)
    username = None

    is_special = models.BooleanField(default=False)
    limit = models.PositiveSmallIntegerField(default=10,blank=True,null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

apps/file/models.py
from django.db import models
from accounts.models import User

# Create your models here.
class UserFile(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    slug = models.SlugField(blank=True, null=True)
    owner =  models.ForeignKey(User,blank=True,null=True,on_delete=models.SET_NULL)
    file = models.FileField(upload_to="files/%Y-%m-%d")
    views = models.ManyToManyField("IpAddress", blank=True, related_name="hits")
    def __str__(self):
        return self.title

class IpAddress(models.Model):
    ip_address = models.GenericIPAddressField()
    def __str__(self) -> str:
        return self.ip_address

apps/accounts/forms.py
from django import  forms
from  django.contrib.auth.forms import UserCreationForm
from accounts.models import User



class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')

apps/file/forms.py
from django import forms
from file.models import UserFile

class FileForm(forms.ModelForm):
    class Meta:
        model = UserFile
        fields = ("title","description","slug","owner","file")

apps/accounts/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import  TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .mixins import SetSpecialMixin
from file.models import User



# Set special page
class SetSpecial(LoginRequiredMixin, SetSpecialMixin, TemplateView):
    '''
        Promote a user as special user
    '''
    template_name = "account/SetSpecial.html"
    def get(self,request):
        user = get_object_or_404(User, email= self.request.user.email, id= self.request.user.id)
        user.is_special = True
        user.limit = 50
        user.save()
        messages.success(self.request, 'from now on, you are a special user')
        return redirect("file:home")


#404 page
def handler404(request,exception):
    return render(request,"404/404.html")

apps/file/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import View, ListView, DetailView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import FileResponse
from django.utils.text import slugify

from file.models import UserFile
from accounts.models import User
from .forms import FileForm
from .mixins import LimitMixin

class FileList(LoginRequiredMixin, ListView):
    '''A list of all uploaded files from a user'''
    template_name = "file/list.html"
    context_object_name = "files"

    def get_queryset(self):
        object = UserFile.objects.filter(owner= self.request.user)
        return object


class AddFile(LoginRequiredMixin, LimitMixin, FormView):
    '''Add a new file'''
    template_name = "file/add.html"
    form_class = FileForm
    success_url = "file:file-list"

    @transaction.atomic()
    def form_valid(self, form):
        form = self.form_class(self.request.POST, self.request.FILES)
        form = form.save(commit=False)

        form.slug = slugify(form.title)
        form.owner = self.request.user

        if self.request.user.is_special and form.file.size < 10485760:
                self.request.user.limit = self.request.user.limit - 1
                self.request.user.save()
                form.save()
                return redirect(self.success_url)

        if form.file.size < 5242880 :
                self.request.user.limit = self.request.user.limit - 1
                self.request.user.save()
                form.save()
                return redirect(self.success_url)

        return redirect(self.success_url)


class DetailFile(DetailView):
    '''Detail page of a file'''
    template_name = "file/detail.html"

    def get_object(self):
        object = get_object_or_404(UserFile, id=self.kwargs["id"], slug=self.kwargs["slug"])
        ip_address = self.request.user.ip_address
        # add ip to the views
        if ip_address not in object.views.all():
            object.views.add(ip_address)

        return object

# File download view
class FileDownload(View):
    def get(self, request, id, slug, *args, **kwargs):
        object = get_object_or_404(UserFile, id= id, slug=slug)
        return FileResponse(object.file, as_attachment=True)

# File delete view
@transaction.atomic()
def DeleteFile(request, id, slug):
    object = get_object_or_404(UserFile, id= id, slug= slug, owner= request.user)
    object.delete()
    request.user.limit = request.user.limit + 1
    request.user.save()
    return redirect('file:file-list')

apps/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>{%block title%}{%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
{% include 'base/navbar.html' %}
<div class="container">
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
    <br>
<div class="container ">
    <div class="shadow p-4 mb-5 bg-body rounded">
        {%block body%}
        {%endblock%}
    </div>
</div>
</div>
</body>
</html>

apps/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{%url 'file:file-list'%}">Uploader</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{%url 'file:add-file' %}">Add</a>
        {%if request.user.is_special == False%}
          <a class="nav-link" href="{%url 'account:set-special' %}">Special User</a>
        {%endif%}
          <a class="nav-link" href="{%url 'account_logout'%}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'account_signup'%}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'account_login'%}">Login</a>
        </li>
      {% endif %}
      </ul>
    </div>
  </div>
</nav>

apps/templates/file/add.html
{%extends 'base/base.html' %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Add File{%endblock%}
</head>
<body>
{%block body%}

{% if request.user.is_special %}
    <h4>You can upload files less than 10 MBs</h4>
{%else%}
    <h4>You can upload files less than 5 MBs</h4>
{% endif %}

<hr>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.title|as_crispy_field }}
        <br>
        {{ form.description|as_crispy_field }}
        <br>
        {{ form.file|as_crispy_field }}
        <br>
        <input type="submit" value="Save" class="btn btn-success">
        <br>
</form>
{%endblock%}
</body>
</html>

apps/templates/file/detail.html
{%extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}File Detail{%endblock%}

</head>
<body>
{%block body%}
<br>
    <h3>Title: {{object.title}}</h3>  <br><hr>
    <p>Description: {{object.description}}</p><hr>
    <div>
    <h6 style="display: inline;">Address: </h6>
        <p style="display: inline;" id="demo">{{ request.META.HTTP_HOST }}/detail/{{object.id}}/{{object.slug}}/ </p>
    <input style="width:90px; height: 12x;" class="btn btn-secondary" value="Copy Url" onclick="copy('demo')"/>
    </div>
    <script>
            function copy(element_id){
          var aux = document.createElement("div");
          aux.setAttribute("contentEditable", true);
          aux.innerHTML = document.getElementById(element_id).innerHTML;
          aux.setAttribute("onfocus", "document.execCommand('selectAll',false,null)");
          document.body.appendChild(aux);
          aux.focus();
          document.execCommand("copy");
          document.body.removeChild(aux);}
    </script>
    <hr>
        Download link:   <a href="{% url 'file:download-file' object.id object.slug%}" style="width: 90px;" type="submit" class="btn btn-secondary">Download</a>
    <hr>
    <h6> Viewed by {{object.views.count}} person</h6><hr>
    <h6> Uploaded by: {{object.owner}}</h6><hr>
{%endblock%}
</body>

</html>

apps/templates/file/list.html
{%extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%block title%}Home{%endblock%}

</head>
<body>
{%block body%}
<div class="container">
    Limit: {%if request.user.is_special%}
        {{request.user.limit}}/50
    {%else%}
        {{request.user.limit}}/10
    {%endif%}

    <br>Is special: {{request.user.is_special}}

    <br><a href="{%url 'file:add-file' %}">Add file</a>
    <hr>
    {% for file in files %}
    <div class="text-center">
        <div class="row align-items-start">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-sm">
                            Name: {{file.title}}
                        </div>
                        <div class="col-sm">
                            Slug: {{file.slug}}
                        </div>
                        <div class="col-sm">
                            <a href="{%url 'file:file-detail' file.id file.slug %}" class="btn btn-secondary">Preview</a>
                            <a href="{%url 'file:delete-file' file.id file.slug%}" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                </li>
                <br>
            </ul>
        </div>
        {% empty %}
        <p>you haven't uploaded any file yet...</p>
        <a href="{%url 'file:add-file'%}">Add new file</a>
    </div>
    {%endfor%}
</div>
<br>
</div>

{%endblock%}
</body>
</html>